group 'com.oneplusdream.flutter_aws_chime'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.oneplusdream.flutter_aws_chime'
    compileSdk 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    defaultConfig {
        minSdk 23
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test:2.4.0'
    testImplementation 'org.mockito:mockito-core:5.0.0'
    implementation 'software.aws.chimesdk:amazon-chime-sdk:0.25.5'
    implementation 'software.aws.chimesdk:amazon-chime-sdk-media:0.25.4'
    implementation 'androidx.appcompat:appcompat:1.3.0'
}
